spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuanvats00562@fpt.edu.vn
spring.mail.password=lymc twyh mvqi wddq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
